WASB_ROOT: ${hydra:runtime.cwd}
defaults:
        - _self_
        - runner: eval
        - dataset: tabletennis
        - model: wasb
        - dataloader: default
        - detector: tracknetv2
        - transform: default
        - tracker: online
hydra:
  run:
    dir: ${WASB_ROOT}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
output_dir:
seed: 1234

