defaults:
        - _self_
        - global
        - runner: inference
        - model: blurball
        - dataset: tabletennis
        - dataloader: default
        - detector: blurball
        - transform: default
        - tracker: online_blur
hydra:
  run:
    dir: ${WASB_ROOT}/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
output_dir: foul_1_test_jui
seed: 1234
